# Generated by Django 5.2 on 2025-05-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepoint',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='point_type',
            field=models.CharField(choices=[('origin', 'Origin'), ('transit', 'Transit'), ('destination', 'Destination')], default='transit', max_length=20),
        ),
        migrations.AddField(
            model_name='shippingroutequery',
            name='transport_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
